export const COUNTRIES = [
  { name: "Afghanistan", iso2: "AF", phone_prefix: "93" },
  { name: "Albania", iso2: "AL", phone_prefix: "355" },
  { name: "Algeria", iso2: "DZ", phone_prefix: "213" },
  { name: "American Samoa", iso2: "AS", phone_prefix: "1-684" },
  { name: "Andorra", iso2: "AD", phone_prefix: "376" },
  { name: "Angola", iso2: "AO", phone_prefix: "244" },
  { name: "Anguilla", iso2: "AI", phone_prefix: "1-264" },
  { name: "Antarctica", iso2: "AQ", phone_prefix: "672" },
  { name: "Antigua and Barbuda", iso2: "AG", phone_prefix: "1-268" },
  { name: "Argentina", iso2: "AR", phone_prefix: "54" },
  { name: "Armenia", iso2: "AM", phone_prefix: "374" },
  { name: "Aruba", iso2: "AW", phone_prefix: "297" },
  { name: "Australia", iso2: "AU", phone_prefix: "61" },
  { name: "Austria", iso2: "AT", phone_prefix: "43" },
  { name: "Azerbaijan", iso2: "AZ", phone_prefix: "994" },
  { name: "Bahamas", iso2: "BS", phone_prefix: "1-242" },
  { name: "Bahrain", iso2: "BH", phone_prefix: "973" },
  { name: "Bangladesh", iso2: "BD", phone_prefix: "880" },
  { name: "Barbados", iso2: "BB", phone_prefix: "1-246" },
  { name: "Belarus", iso2: "BY", phone_prefix: "375" },
  { name: "Belgium", iso2: "BE", phone_prefix: "32" },
  { name: "Belize", iso2: "BZ", phone_prefix: "501" },
  { name: "Benin", iso2: "BJ", phone_prefix: "229" },
  { name: "Bermuda", iso2: "BM", phone_prefix: "1-441" },
  { name: "Bhutan", iso2: "BT", phone_prefix: "975" },
  { name: "Bolivia", iso2: "BO", phone_prefix: "591" },
  { name: "Bosnia and Herzegovina", iso2: "BA", phone_prefix: "387" },
  { name: "Botswana", iso2: "BW", phone_prefix: "267" },
  { name: "Brazil", iso2: "BR", phone_prefix: "55" },
  { name: "British Indian Ocean Territory", iso2: "IO", phone_prefix: "246" },
  { name: "British Virgin Islands", iso2: "VG", phone_prefix: "1-284" },
  { name: "Brunei", iso2: "BN", phone_prefix: "673" },
  { name: "Bulgaria", iso2: "BG", phone_prefix: "359" },
  { name: "Burkina Faso", iso2: "BF", phone_prefix: "226" },
  { name: "Burundi", iso2: "BI", phone_prefix: "257" },
  { name: "Cambodia", iso2: "KH", phone_prefix: "855" },
  { name: "Cameroon", iso2: "CM", phone_prefix: "237" },
  { name: "Canada", iso2: "CA", phone_prefix: "1" },
  { name: "Cape Verde", iso2: "CV", phone_prefix: "238" },
  { name: "Caribbean Netherlands", iso2: "BQ", phone_prefix: "599" },
  { name: "Cayman Islands", iso2: "KY", phone_prefix: "1-345" },
  { name: "Central African Republic", iso2: "CF", phone_prefix: "236" },
  { name: "Chad", iso2: "TD", phone_prefix: "235" },
  { name: "Chile", iso2: "CL", phone_prefix: "56" },
  { name: "China", iso2: "CN", phone_prefix: "86" },
  { name: "Christmas Island", iso2: "CX", phone_prefix: "61" },
  { name: "Cocos (Keeling) Islands", iso2: "CC", phone_prefix: "61" },
  { name: "Colombia", iso2: "CO", phone_prefix: "57" },
  { name: "Comoros", iso2: "KM", phone_prefix: "269" },
  { name: "Cook Islands", iso2: "CK", phone_prefix: "682" },
  { name: "Costa Rica", iso2: "CR", phone_prefix: "506" },
  { name: "Croatia", iso2: "HR", phone_prefix: "385" },
  { name: "Cuba", iso2: "CU", phone_prefix: "53" },
  { name: "Curaçao", iso2: "CW", phone_prefix: "599" },
  { name: "Cyprus", iso2: "CY", phone_prefix: "357" },
  { name: "Czechia", iso2: "CZ", phone_prefix: "420" },
  { name: "Democratic Republic of the Congo", iso2: "CD", phone_prefix: "243" },
  { name: "Denmark", iso2: "DK", phone_prefix: "45" },
  { name: "Djibouti", iso2: "DJ", phone_prefix: "253" },
  { name: "Dominica", iso2: "DM", phone_prefix: "1-767" },
  { name: "Dominican Republic", iso2: "DO", phone_prefix: "1-809" },
  { name: "Ecuador", iso2: "EC", phone_prefix: "593" },
  { name: "Egypt", iso2: "EG", phone_prefix: "20" },
  { name: "El Salvador", iso2: "SV", phone_prefix: "503" },
  { name: "Equatorial Guinea", iso2: "GQ", phone_prefix: "240" },
  { name: "Eritrea", iso2: "ER", phone_prefix: "291" },
  { name: "Estonia", iso2: "EE", phone_prefix: "372" },
  { name: "Eswatini", iso2: "SZ", phone_prefix: "268" },
  { name: "Ethiopia", iso2: "ET", phone_prefix: "251" },
  { name: "Falkland Islands", iso2: "FK", phone_prefix: "500" },
  { name: "Faroe Islands", iso2: "FO", phone_prefix: "298" },
  { name: "Fiji", iso2: "FJ", phone_prefix: "679" },
  { name: "Finland", iso2: "FI", phone_prefix: "358" },
  { name: "France", iso2: "FR", phone_prefix: "33" },
  { name: "French Guiana", iso2: "GF", phone_prefix: "594" },
  { name: "French Polynesia", iso2: "PF", phone_prefix: "689" },
  { name: "Gabon", iso2: "GA", phone_prefix: "241" },
  { name: "Gambia", iso2: "GM", phone_prefix: "220" },
  { name: "Georgia", iso2: "GE", phone_prefix: "995" },
  { name: "Germany", iso2: "DE", phone_prefix: "49" },
  { name: "Ghana", iso2: "GH", phone_prefix: "233" },
  { name: "Gibraltar", iso2: "GI", phone_prefix: "350" },
  { name: "Greece", iso2: "GR", phone_prefix: "30" },
  { name: "Greenland", iso2: "GL", phone_prefix: "299" },
  { name: "Grenada", iso2: "GD", phone_prefix: "1-473" },
  { name: "Guadeloupe", iso2: "GP", phone_prefix: "590" },
  { name: "Guam", iso2: "GU", phone_prefix: "1-671" },
  { name: "Guatemala", iso2: "GT", phone_prefix: "502" },
  { name: "Guernsey", iso2: "GG", phone_prefix: "44-1481" },
  { name: "Guinea", iso2: "GN", phone_prefix: "224" },
  { name: "Guinea-Bissau", iso2: "GW", phone_prefix: "245" },
  { name: "Guyana", iso2: "GY", phone_prefix: "592" },
  { name: "Haiti", iso2: "HT", phone_prefix: "509" },
  { name: "Honduras", iso2: "HN", phone_prefix: "504" },
  { name: "Hong Kong", iso2: "HK", phone_prefix: "852" },
  { name: "Hungary", iso2: "HU", phone_prefix: "36" },
  { name: "Iceland", iso2: "IS", phone_prefix: "354" },
  { name: "India", iso2: "IN", phone_prefix: "91" },
  { name: "Indonesia", iso2: "ID", phone_prefix: "62" },
  { name: "Iran", iso2: "IR", phone_prefix: "98" },
  { name: "Iraq", iso2: "IQ", phone_prefix: "964" },
  { name: "Ireland", iso2: "IE", phone_prefix: "353" },
  { name: "Isle of Man", iso2: "IM", phone_prefix: "44-1624" },
  { name: "Israel", iso2: "IL", phone_prefix: "972" },
  { name: "Italy", iso2: "IT", phone_prefix: "39" },
  { name: "Ivory Coast", iso2: "CI", phone_prefix: "225" },
  { name: "Jamaica", iso2: "JM", phone_prefix: "1-876" },
  { name: "Japan", iso2: "JP", phone_prefix: "81" },
  { name: "Jersey", iso2: "JE", phone_prefix: "44-1534" },
  { name: "Jordan", iso2: "JO", phone_prefix: "962" },
  { name: "Kazakhstan", iso2: "KZ", phone_prefix: "7" },
  { name: "Kenya", iso2: "KE", phone_prefix: "254" },
  { name: "Kiribati", iso2: "KI", phone_prefix: "686" },
  { name: "Kuwait", iso2: "KW", phone_prefix: "965" },
  { name: "Kyrgyzstan", iso2: "KG", phone_prefix: "996" },
  { name: "Laos", iso2: "LA", phone_prefix: "856" },
  { name: "Latvia", iso2: "LV", phone_prefix: "371" },
  { name: "Lebanon", iso2: "LB", phone_prefix: "961" },
  { name: "Lesotho", iso2: "LS", phone_prefix: "266" },
  { name: "Liberia", iso2: "LR", phone_prefix: "231" },
  { name: "Libya", iso2: "LY", phone_prefix: "218" },
  { name: "Liechtenstein", iso2: "LI", phone_prefix: "423" },
  { name: "Lithuania", iso2: "LT", phone_prefix: "370" },
  { name: "Luxembourg", iso2: "LU", phone_prefix: "352" },
  { name: "Macau", iso2: "MO", phone_prefix: "853" },
  { name: "Madagascar", iso2: "MG", phone_prefix: "261" },
  { name: "Malawi", iso2: "MW", phone_prefix: "265" },
  { name: "Malaysia", iso2: "MY", phone_prefix: "60" },
  { name: "Maldives", iso2: "MV", phone_prefix: "960" },
  { name: "Mali", iso2: "ML", phone_prefix: "223" },
  { name: "Malta", iso2: "MT", phone_prefix: "356" },
  { name: "Marshall Islands", iso2: "MH", phone_prefix: "692" },
  { name: "Martinique", iso2: "MQ", phone_prefix: "596" },
  { name: "Mauritania", iso2: "MR", phone_prefix: "222" },
  { name: "Mauritius", iso2: "MU", phone_prefix: "230" },
  { name: "Mayotte", iso2: "YT", phone_prefix: "262" },
  { name: "Mexico", iso2: "MX", phone_prefix: "52" },
  { name: "Micronesia", iso2: "FM", phone_prefix: "691" },
  { name: "Moldova", iso2: "MD", phone_prefix: "373" },
  { name: "Monaco", iso2: "MC", phone_prefix: "377" },
  { name: "Mongolia", iso2: "MN", phone_prefix: "976" },
  { name: "Montenegro", iso2: "ME", phone_prefix: "382" },
  { name: "Montserrat", iso2: "MS", phone_prefix: "1-664" },
  { name: "Morocco", iso2: "MA", phone_prefix: "212" },
  { name: "Mozambique", iso2: "MZ", phone_prefix: "258" },
  { name: "Myanmar", iso2: "MM", phone_prefix: "95" },
  { name: "Namibia", iso2: "NA", phone_prefix: "264" },
  { name: "Nauru", iso2: "NR", phone_prefix: "674" },
  { name: "Nepal", iso2: "NP", phone_prefix: "977" },
  { name: "Netherlands", iso2: "NL", phone_prefix: "31" },
  { name: "New Caledonia", iso2: "NC", phone_prefix: "687" },
  { name: "New Zealand", iso2: "NZ", phone_prefix: "64" },
  { name: "Nicaragua", iso2: "NI", phone_prefix: "505" },
  { name: "Niger", iso2: "NE", phone_prefix: "227" },
  { name: "Nigeria", iso2: "NG", phone_prefix: "234" },
  { name: "Niue", iso2: "NU", phone_prefix: "683" },
  { name: "Norfolk Island", iso2: "NF", phone_prefix: "672" },
  { name: "North Korea", iso2: "KP", phone_prefix: "850" },
  { name: "North Macedonia", iso2: "MK", phone_prefix: "389" },
  { name: "Northern Mariana Islands", iso2: "MP", phone_prefix: "1-670" },
  { name: "Norway", iso2: "NO", phone_prefix: "47" },
  { name: "Oman", iso2: "OM", phone_prefix: "968" },
  { name: "Pakistan", iso2: "PK", phone_prefix: "92" },
  { name: "Palau", iso2: "PW", phone_prefix: "680" },
  { name: "Palestine", iso2: "PS", phone_prefix: "970" },
  { name: "Panama", iso2: "PA", phone_prefix: "507" },
  { name: "Papua New Guinea", iso2: "PG", phone_prefix: "675" },
  { name: "Paraguay", iso2: "PY", phone_prefix: "595" },
  { name: "Peru", iso2: "PE", phone_prefix: "51" },
  { name: "Philippines", iso2: "PH", phone_prefix: "63" },
  { name: "Poland", iso2: "PL", phone_prefix: "48" },
  { name: "Portugal", iso2: "PT", phone_prefix: "351" },
  { name: "Puerto Rico", iso2: "PR", phone_prefix: "1-787" },
  { name: "Qatar", iso2: "QA", phone_prefix: "974" },
  { name: "Republic of the Congo", iso2: "CG", phone_prefix: "242" },
  { name: "Réunion", iso2: "RE", phone_prefix: "262" },
  { name: "Romania", iso2: "RO", phone_prefix: "40" },
  { name: "Russia", iso2: "RU", phone_prefix: "7" },
  { name: "Rwanda", iso2: "RW", phone_prefix: "250" },
  { name: "Saint Barthélemy", iso2: "BL", phone_prefix: "590" },
  { name: "Saint Helena", iso2: "SH", phone_prefix: "290" },
  { name: "Saint Kitts and Nevis", iso2: "KN", phone_prefix: "1-869" },
  { name: "Saint Lucia", iso2: "LC", phone_prefix: "1-758" },
  { name: "Saint Martin", iso2: "MF", phone_prefix: "590" },
  { name: "Saint Pierre and Miquelon", iso2: "PM", phone_prefix: "508" },
  { name: "Saint Vincent and the Grenadines", iso2: "VC", phone_prefix: "1-784" },
  { name: "Samoa", iso2: "WS", phone_prefix: "685" },
  { name: "San Marino", iso2: "SM", phone_prefix: "378" },
  { name: "Sao Tome and Principe", iso2: "ST", phone_prefix: "239" },
  { name: "Saudi Arabia", iso2: "SA", phone_prefix: "966" },
  { name: "Senegal", iso2: "SN", phone_prefix: "221" },
  { name: "Serbia", iso2: "RS", phone_prefix: "381" },
  { name: "Seychelles", iso2: "SC", phone_prefix: "248" },
  { name: "Sierra Leone", iso2: "SL", phone_prefix: "232" },
  { name: "Singapore", iso2: "SG", phone_prefix: "65" },
  { name: "Sint Maarten", iso2: "SX", phone_prefix: "1-721" },
  { name: "Slovakia", iso2: "SK", phone_prefix: "421" },
  { name: "Slovenia", iso2: "SI", phone_prefix: "386" },
  { name: "Solomon Islands", iso2: "SB", phone_prefix: "677" },
  { name: "Somalia", iso2: "SO", phone_prefix: "252" },
  { name: "South Africa", iso2: "ZA", phone_prefix: "27" },
  { name: "South Korea", iso2: "KR", phone_prefix: "82" },
  { name: "South Sudan", iso2: "SS", phone_prefix: "211" },
  { name: "Spain", iso2: "ES", phone_prefix: "34" },
  { name: "Sri Lanka", iso2: "LK", phone_prefix: "94" },
  { name: "Sudan", iso2: "SD", phone_prefix: "249" },
  { name: "Suriname", iso2: "SR", phone_prefix: "597" },
  { name: "Svalbard and Jan Mayen", iso2: "SJ", phone_prefix: "47" },
  { name: "Sweden", iso2: "SE", phone_prefix: "46" },
  { name: "Switzerland", iso2: "CH", phone_prefix: "41" },
  { name: "Syria", iso2: "SY", phone_prefix: "963" },
  { name: "Taiwan", iso2: "TW", phone_prefix: "886" },
  { name: "Tajikistan", iso2: "TJ", phone_prefix: "992" },
  { name: "Tanzania", iso2: "TZ", phone_prefix: "255" },
  { name: "Thailand", iso2: "TH", phone_prefix: "66" },
  { name: "Timor-Leste", iso2: "TL", phone_prefix: "670" },
  { name: "Togo", iso2: "TG", phone_prefix: "228" },
  { name: "Tokelau", iso2: "TK", phone_prefix: "690" },
  { name: "Tonga", iso2: "TO", phone_prefix: "676" },
  { name: "Trinidad and Tobago", iso2: "TT", phone_prefix: "1-868" },
  { name: "Tunisia", iso2: "TN", phone_prefix: "216" },
  { name: "Turkey", iso2: "TR", phone_prefix: "90" },
  { name: "Turkmenistan", iso2: "TM", phone_prefix: "993" },
  { name: "Turks and Caicos Islands", iso2: "TC", phone_prefix: "1-649" },
  { name: "Tuvalu", iso2: "TV", phone_prefix: "688" },
  { name: "Uganda", iso2: "UG", phone_prefix: "256" },
  { name: "Ukraine", iso2: "UA", phone_prefix: "380" },
  { name: "United Arab Emirates", iso2: "AE", phone_prefix: "971" },
  { name: "United Kingdom", iso2: "GB", phone_prefix: "44" },
  { name: "United States", iso2: "US", phone_prefix: "1" },
  { name: "Uruguay", iso2: "UY", phone_prefix: "598" },
  { name: "Uzbekistan", iso2: "UZ", phone_prefix: "998" },
  { name: "Vanuatu", iso2: "VU", phone_prefix: "678" },
  { name: "Vatican City", iso2: "VA", phone_prefix: "379" },
  { name: "Venezuela", iso2: "VE", phone_prefix: "58" },
  { name: "Vietnam", iso2: "VN", phone_prefix: "84" },
  { name: "Wallis and Futuna", iso2: "WF", phone_prefix: "681" },
  { name: "Yemen", iso2: "YE", phone_prefix: "967" },
  { name: "Zambia", iso2: "ZM", phone_prefix: "260" },
  { name: "Zimbabwe", iso2: "ZW", phone_prefix: "263" }
];
